/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.di

import com.di.logic.Evaluation
import com.typesafe.config.{Config, ConfigFactory}
import org.apache.log4j.{Level, LogManager, Logger}
import org.apache.spark.sql.SparkSession
import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatest.matchers.must.Matchers
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite with Matchers {
  val config: Config = ConfigFactory
    .load("application.conf")
    .getConfig("main")

  val logger: Logger = LogManager.getRootLogger
  logger.setLevel(Level.WARN)

  implicit val spark: SparkSession = SparkSession
    .builder()
    .appName("test")
    .master("local[*]")
    .getOrCreate()

  import spark.implicits._


  test("lala") {
    val values = TestValuesGenerator.generateRandomTestInput

    val evaluation = new Evaluation

    val result = evaluation.algorithmV2(values.allValues.toDF("key", "value")).collect()

    result must contain theSameElementsAs values.valuesToFind
  }
}
